language: node_js
node_js:
  - '8'
  - '7'

dist: trusty
sudo: false

env:
  global:
    - secure: h4AF0WAnVhFgwhpcmh52Tsa/nD10cZBnS1vZ8VTHoUp7w6Il5R4MVyxuRuyvisQyRG4UI67RzF3wOb0kG0YW2WY9bT4Omt31oeqQVvKurLCx/EJT22ll/9QsCdrkbje9Lc1QGRFrWEnxs3pzucqyvAX8kSK9o7FhIK1NyYqbr/B7z9y3vmibZBBssfbbY8pppl4xqjb4L5gVIP33FRUi637u0JP3aKi+WacFtS8kXxY9ikXFD4w2CPHI2GTSMDQSuyUB1r6FgMBwDjZGypofYDeXezGd2ktSFN6J8UsuHIHuOb6U6WVbptcL/Yg7Ai3pCRONaeAWNQ8NeckObLxu99U8qW0CFvZeAt+jym9M063tUxcGBSkDjxd+Me84qgchzQT+tQa5tFAT0BqyMyN4g4VC4XhKIDkTM2MsYApn97b4n9aL51SCA3N9Jcrbys5/2NmEA7hdPaHjDUd+BisaCcDIPUcYI+Qzkm+e5/EY1a8v2qxLytcKsNyDXMWWWq+/vQKi1sO5h60htkeAJGnVL5FakXid4nJmdQM5oK1xzFX9tMAo4WKZW7ojDASQm8MU/Hgh+gQLJXPdyak4GUVII+c/ebkXbC4dcda6PglasyGLNmqxnqa2qMbHvaANZmG4BLnxUP/HsjKblZiydRvtlqK1qvSjbkJlCc7TRjqfbEU=
    - secure: Int5wzJ3ID0Fr55FHMsTAHDnRTDLJZldpHAj31J4Klf44pD6+DiKHnG3X8CWKRP+BpcxGWqq0PwmETsfScOPeAwv6a85m0oFHBzSyTpOdwxwMx26be6kcuED+5ynp7asm8wlmDRenMJlE4AvCUlePy8tMBtmso3Gb+s38UdLZeHFDfF2oLsdH1tAfOSq2cfIT+eGrXLlgC6kskTHzBx4fd6h+RQ93cyo+pDaYslEeryr9Oh0GqPy8ybD4xgPdi07H4yukR9hRz0Wg7UayC3eEbA/dIJtT0ixp40lhsEZlasZvZvBVraxCTwauAVgju/UTuIK9/f4piHx0AvQsXgmOoImNzi0LdLCLhYTwR+qhD/wcG0r6ZZMxAo9xvwhaLQk4pa0rLPkZI+MrB7tIfS+q5ein1KH8fzRhPrJNNrt0Q4qfbKPz1WhSyslKFdjp4eRcPZ7dpwzhdoo1o1RqIk56IDQix5mAAKESZLrJbOWZRiVs1moAi7NsqSPv4BNbXK5wlmEf0uJbti8LfsBc64abA8eEfCH2Losti94QnUzJvGSmkpjl8jTxsO0eLHQwVEpeLT8QikhlsC+hNrEQr9Fmn4Koz4SdzXew/q08fbbs89KX6H1aDU7JNLoZnjNuvXLKpIBzr8m3jfRfiOTd1Nhsd+Hwwt8eWOIosOL61Np1Oc=
    - secure: j3RMRY61aU3Za2SmER108aJVCSQQTxPyoM5IOTVaTkspMG8lzNgfnXvVtdkaSifPce/1UKat3SG92eZKVB8IEB7oLRHe2PXoUqBoQR5LgUBFNLQeQxTYVRayRcj2wgSrimzCgkPwWGI1d6hTfhIzrR+Wjl0NmTZyvNexJOxe4sVAMBFqrYqIm/JZYgizVVgPac3JV/lLUIXdZXHPpZWtyrk8b30aD/E8MO4ayyZItCsEYG4D/jxSw0BjbztKCAnraGk0A05y+B5jpwRFnaUhpubc/cAF7pWMsxyl1ZbC27IYwK847BOlPY3Q852TSB5WQSv/OGb0rTTW9PhqCpDdA7k4EGWRM9O6om1WfZggv53yXTXc8R/o6f2gBPkAwmu1tm2XiXRnMjnbPTGt+RP1v13b9P0O5f1NBdnDevHI9yQC7pfrTq52sbma4rnhuIZQT+55Ad0bV6naprAQpz+0ijms00D7Dx0uWuAUFXGghy6LhvVPIhyvPIQyuhKKYghnl3wucDViqLXK9rLdxJKEAz4VvMgUPZsqMFtEFD/v1Ru9aV314zqQoCjNYN9/SgsLPk2ozdFbQrC5FTO7Onmuob1V3VFaB+qoco7Ep8c/f2lvI4AUbuR+9JLPFGpsyNZDUI8cQdxc113WntgqOIQQtR9kfJUdYMjcWCIP0jYfU7U=

cache:
  directories:
    - node_modules

install:
  - npm install --no-save
  - npm install -g npm-cli-login

before_script:
  - echo $TRAVIS_COMMIT_MESSAGE | npm run commitlint

script:
  - npm run lint

after_success:
  - |
    if [[ $TRAVIS_BRANCH = develop ]]; then
      npm-cli-login
      npm run canary
      npm logout
    fi
