language: node_js
node_js:
  - "8"
  - "7"

dist: trusty
sudo: false

cache:
  directories:
    - "node_modules"

install:
  - npm install --no-save
  - npm install -g npm-cli-login

before_script:
  - echo $TRAVIS_COMMIT_MESSAGE | npm run commitlint

script:
  - npm run lint

after_success:
  - npm-cli-login
  - npm run canary
