language: node_js
node_js:
  - "8"

dist: trusty
sudo: false

cache:
  directories:
    - "node_modules"

install:
  - npm install --no-save

before_script:
  - echo $TRAVIS_COMMIT_MESSAGE | npm run commitlint

script:
  - npm run lint
  - npm run test:ci
